### ISSUE TITLE
Maintain?

### ISSUE THREAD

**Issue by stephenlacy** [millermedeiros/node-ant#8]
Is this project been maintained in any way?

**Comment by millermedeiros** [comment]
nope.. I used this a couple times in the past but moved on to other tools (Grunt, Gulp, npm modules, etc..) since starting the Java process is very slow and the way to write the tasks is very limited.

**Comment by stephenlacy** [comment]
Ah, I was looking for a java ant wrapper for cordova android projects to run ant as a npm global.

I do use gulp as well (as my gh profile might indicate :laughing: )
